# 00. PyTorch Fundamentals

In [11]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1


## Introduction to Tensors

### Creating tensors

In [12]:
# scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [13]:
scalar.ndim

0

In [14]:
# Get tensor back as Python int
scalar.item()

7

In [15]:
# Vector
vector = torch.tensor([3,4])
vector

tensor([3, 4])

In [16]:
vector.ndim

1

In [17]:
vector.shape

torch.Size([2])

In [18]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [19]:
MATRIX.ndim

2

In [20]:
MATRIX[1]

tensor([ 9, 10])

In [22]:
MATRIX.shape

torch.Size([2, 2])

In [23]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [3,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [3, 4, 5]]])

In [24]:
TENSOR.ndim

3

In [25]:
TENSOR.shape

torch.Size([1, 3, 3])

In [26]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [3, 4, 5]])

In [29]:
TENSOR[0,0]

tensor([1, 2, 3])

In [36]:
TENSOR2 = torch.tensor([[[1,2,3,4,5],
                         [2,3,4,5,6],
                        [3,4,5,6,7],
                        [4,5,6,7,8]]])
TENSOR2

tensor([[[1, 2, 3, 4, 5],
         [2, 3, 4, 5, 6],
         [3, 4, 5, 6, 7],
         [4, 5, 6, 7, 8]]])

In [37]:
TENSOR2.shape

torch.Size([1, 4, 5])

### Random tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [44]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1599, 0.7427, 0.7948, 0.6214],
        [0.4547, 0.5424, 0.6085, 0.5258],
        [0.2695, 0.6385, 0.3396, 0.3531]])

In [45]:
random_tensor.ndim

2

In [48]:
# Create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, colour channels (R, G, B)
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([3, 224, 224]))

### Zero and ones

In [49]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [50]:
# Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [51]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [54]:
# torch.range() is depreicated, instead use torch.arange()
one_to_ten = torch.arange(start=1, end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Three major things to make sure when dealing with tensors in PyTorch

1. Tensors not in right datatype
2. Tensors not in right shape
3. Tensors not on the right device

In [59]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                              device=None, # what device is your tensor on
                              requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [60]:
float_32_tensor.dtype

torch.float32

In [61]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [65]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information fom tensors (tensor attributes)

1. datatype - `tensor.dtype`
2. shape - `tensor.shape`
3. device - `tensor.device`

In [88]:
# Create a tensor
some_tensor = torch.rand(size=(3,4))
some_tensor

tensor([[0.2960, 0.7429, 0.4960, 0.1909],
        [0.4105, 0.1379, 0.4345, 0.8660],
        [0.9006, 0.4456, 0.3602, 0.7803]])

In [89]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape os tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2960, 0.7429, 0.4960, 0.1909],
        [0.4105, 0.1379, 0.4345, 0.8660],
        [0.9006, 0.4456, 0.3602, 0.7803]])
Datatype of tensor: torch.float32
Shape os tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:

* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [167]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [173]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [174]:
tensor

tensor([1, 2, 3])

In [175]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [176]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [177]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways to performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)


In [169]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [170]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [171]:
tensor

tensor([1, 2, 3])

In [172]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [178]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.42 ms, sys: 781 µs, total: 2.2 ms
Wall time: 1.49 ms


In [180]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 202 µs, sys: 40 µs, total: 242 µs
Wall time: 189 µs


tensor(14)

#### Two main rules when performing matrix multiplication

1. The **inner dimensions** must match:

* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimenstions**:

* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [181]:
torch.matmul(torch.rand(3,2), torch.rand(2,3)).shape

torch.Size([3, 3])

### One of the most commen error in Matrix multiplication is shape error

In [185]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.mm(tensor_A,tensor_B) # torch.mm is the same as torch.matmul and @ (These are aliases for writing less code)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor

In [186]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [187]:
tensor_A.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [189]:
# The Matrix multiplication operation works when tensor_B is transposed
output = torch.matmul(tensor_A,tensor_B.T)
output

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [190]:
#shape of output is equals to the outer dimensions
output.shape

torch.Size([3, 3])