# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7,7)
tensor

tensor([[0.8353, 0.3027, 0.4916, 0.8215, 0.0363, 0.5000, 0.3358],
        [0.8353, 0.9216, 0.1220, 0.0314, 0.6495, 0.6433, 0.2954],
        [0.6178, 0.3277, 0.9269, 0.2665, 0.8927, 0.9614, 0.7969],
        [0.1320, 0.7248, 0.6541, 0.7882, 0.6251, 0.7311, 0.2275],
        [0.5169, 0.6532, 0.9729, 0.4258, 0.5321, 0.8566, 0.4717],
        [0.5747, 0.5720, 0.3180, 0.2022, 0.5287, 0.7583, 0.0577],
        [0.7335, 0.5682, 0.5318, 0.2238, 0.8855, 0.0658, 0.8195]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [9]:
# Create another random tensor

tensor_B = torch.rand(1, 7)

# Perform matrix multiplication 
tensor_C = torch.matmul(tensor,tensor_B.T)

tensor_C

tensor([[1.5335],
        [1.5064],
        [1.6191],
        [1.7296],
        [1.6639],
        [1.3497],
        [1.2643]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [33]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
tensor_A = torch.rand((7, 7), device="cpu")
tensor_B = torch.rand((1, 7), device="cpu")
# Matrix multiply tensors
tensor_C = torch.matmul(tensor_A,tensor_B.T)

tensor_C

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [43]:
# Set random seed on the GPU
#torch.cuda.manual_seed(1234)
torch.mps.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [61]:
# Set random seed
RANDOM_SEED = 1234

torch.manual_seed(RANDOM_SEED)

# Check for access to GPU
device = "mps" if torch.backends.mps.is_available() else "cpu"
print(f"Device : {device}")

# Create two random tensors on GPU
torch.mps.manual_seed(1234)
tensor1 = torch.rand((2, 3), device=device)

torch.mps.manual_seed(1234)
tensor2 = torch.rand((2, 3), device=device)

torch.mps.manual_seed(1234)
tensor1 = torch.rand((2, 3), device="cpu")

torch.mps.manual_seed(1234)
tensor2 = torch.rand((2, 3), device="cpu")

tensor1 = tensor1.to(device)
tensor2 = tensor2.to(device)

tensor1, tensor2

Device : mps


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='mps:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='mps:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [63]:
# Perform matmul on tensor_A and tensor_B

tensor3 = torch.matmul(tensor1,tensor2.T)
tensor3, tensor3.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='mps:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [68]:
# Find max

print(f"Max : {tensor3.max()}")

# Find min

print(f"Min : {tensor3.min()}")


Max : 0.5617256760597229
Min : 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [70]:
# Find arg max
print(f"Index of max: {tensor3.argmax()}")

# Find arg min
print(f"Index of min: {tensor3.argmin()}")

Index of max: 3
Index of min: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [75]:
# Set seed
RANDOM_SEED = 7

torch.manual_seed(7)
# Create random tensor
tensor4 = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor5 = tensor4.squeeze()

# Print out tensors and their shapes
tensor4, tensor4.shape, tensor5 , tensor5.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))